credentials:
  usernames:
    kolbotn:
      name: Kolbotn IL
      password: $2b$12$Yv09xnHmvzJqvf6kWZ0bnOMJ.jwXGM.B9rix14r.yYbJrUIpdB1ou # To be replaced with hashed password
    baasum:
      name: Båsum Boring
      password: $2b$12$SxSdhRwkb2S/iSd18t6bSecDgQy/FfbAgclLX3Bqis0.eXj3vwwye # To be replaced with hashed password
    asplanviak:
      name: Asplan Viak
      password: $2b$12$U5Vz7gDKb/VMKPpk5zyp3OKUPlAdEV9iZTqXSW0LkCjXbjauz6Sza # To be replaced with hashed password
    eptec:
      name: Eptec
      password: $2b$12$N3hi1OAysyUyqY/lDS2FKOwsjROQSjyGMqBnOxyLJSDjlJ79TnlVW # To be replaced with hashed password
cookie:
  expiry_days: 360
  key: some_signature_key
  name: some_cookie_name
